name: DuneCamp

google_analytics: UA-62253510-5

markdown: kramdown

# This flag means that event is still in progress but registration is closed
is_registration_open: true 

# This flag means that event is in progress, otherwise need to transform to cooming soon page
is_in_progress: true

previous_events:
    - name: "Хакатон"
      link: https://ottepel.youcon.ru

other_events:
    - name: "Юкон"
      link: https://youcon.ru

event_date: "12-14 июля 2019"
event_city: "Саратов"
event_location_name: "турбаза 'Дубровка'" 

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
